## Distance Functions

In [1]:
import os
import torch
import torchvision
import torchvision.transforms as transforms
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm

In [2]:
# Creating a sample input data

test_image = np.array(
    [[56, 32, 10, 18],
     [90, 23, 128, 133],
     [24, 26, 178, 200],
     [2, 0, 255, 220]]
)

training_image = np.array(
    [[10, 20, 24, 17],
     [8, 10, 89, 100],
     [12, 16, 178, 170],
     [4, 32, 233, 112]]
)

print(
    f"Test Image:\n\n"
    f"{test_image}\n\n"
    f"Training Image:\n\n"
    f"{training_image}"
)

Test Image:

[[ 56  32  10  18]
 [ 90  23 128 133]
 [ 24  26 178 200]
 [  2   0 255 220]]

Training Image:

[[ 10  20  24  17]
 [  8  10  89 100]
 [ 12  16 178 170]
 [  4  32 233 112]]


### 1. Manhatten Distance (L1 Norm)

In [3]:
# Pixel-wise absolute value differences
def calculate_L1_norm(image1, image2):
    ''' 
    L1 norm formula: sum(abs(a - b)) 
    for all corresponding elements in vectors a and b
    '''
    return np.sum(np.abs(image1 - image2))

l1 = calculate_L1_norm(test_image, training_image)
print(f"L1: {l1}")

L1: 456


### 2. Euclidean Distance (L2 Norm)

In [4]:
# Pixel-wise squared differences and square root of the sum
def calculate_L2_norm(image1, image2):
    ''' 
    L2 norm (Euclidean) formula: sqrt(sum((a - b)**2)) 
    for all corresponding elements in vectors a and b
    '''
    return np.sqrt(np.sum((image1 - image2) ** 2))

l2 = calculate_L2_norm(test_image, training_image)
print(f"L2: {l2}")

L2: 162.11107303327555
